[package]
name = "AdventOfCode"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.12.2"
z3 = "0.19"
z3-sys = { version = "0.10", features = ["gh-release"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "day4_benchmark_2025"
harness = false
